<h2>Fundamentos de R</h2>

<h3>Criação de Variáveis, Função Print, Comentários e Operações Básicas</h3>

In [1]:
resultado <- 3 + 5
print(resultado)

# comentários são escritos com #

multiply <- function(x, y) {
  return(x * y)
}

product <- multiply(4, 6)
print(product)

print(c("Olá", "Mundo!"))
print(paste("O produto de 3 e 4 é:", multiply(3, 4)))


[1] 8
[1] 24
[1] "Olá"    "Mundo!"
[1] "O produto de 3 e 4 é: 12"


<h3>Data Types</h3>

In [2]:
a <- 10 # Número inteiro MAS o R lê como double por padrão
b <- 3.14 # Número decimal

typeof(a)

c <- 25L # ao adicionar o L no final do número, o R entende como inteiro
typeof(c)

texto1 <- "Texto 1"
boolean1 <- TRUE
boolean2 <- FALSE

boolean1 & boolean2 # (porta lógica AND)
boolean1 | boolean2 # (porta lógica OR)

is.numeric(a)
is.character(texto1)
is.logical(boolean1)

x <- "42"
x_num <- as.numeric(x)
y <- 100L
y_text <- as.character(y)

# Também tem a função as.integer, as.double e as.logical. Ao usar uma boolean como número, retorna 1 para TRUE e 0 para FALSE # nolint

#memory.size() tamanho da memória alocada exclusivo do windows
#memory.limit() limite máximo de memória exclusivo do windows
# gc()

# valores especiais: NA (not available), NaN (not a number), Inf (infinito) e Null (ausência de valor) # nolint
# help(function) para receber ajuda sobre uma função específica

[1] "double"

[1] "integer"

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

<h3>Data Structures</h3>

In [3]:
my_vector <- c(100, 200, 400) #Vetores
print(my_vector * 2)
print(my_vector[1])

my_list <- list(
  name = "Henrique",
  age = 21,
  salary = 1300
)

print(my_list["age"])

my_matrix <- matrix(
  c(1, 0, 0, 1),
  nrow = 2,
  ncol = 2
)

print(my_matrix)
print(my_matrix[1, 1]) # linha e coluna, nessa ordem

my_matrix2 <- matrix(
  c(5, 6, 7, 6),
  nrow = 2,
  ncol = 2
)

sumn_of_matrices <- my_matrix + my_matrix2
print(sumn_of_matrices)

print(my_matrix * sumn_of_matrices)

transposed_matrix <- t(my_matrix2)
print(transposed_matrix)

shape_of_matrix <- dim(transposed_matrix)
print(shape_of_matrix)

my_data_frame <- data.frame(
  name = c("Henrique", "Edna", "Claudinei"),
  age = c(21, 55, 57),
  job = c("Estudante", "Professora", "Servidor Público")
)

print(my_data_frame)
print(my_data_frame$name)
print(my_data_frame[2, "age"])


[1] 200 400 800
[1] 100
$age
[1] 21

     [,1] [,2]
[1,]    1    0
[2,]    0    1
[1] 1
     [,1] [,2]
[1,]    6    7
[2,]    6    7
     [,1] [,2]
[1,]    6    0
[2,]    0    7
     [,1] [,2]
[1,]    5    6
[2,]    7    6
[1] 2 2
       name age              job
1  Henrique  21        Estudante
2      Edna  55       Professora
3 Claudinei  57 Servidor Público
[1] "Henrique"  "Edna"      "Claudinei"
[1] 55


<h3>Control Flow</h3>

In [4]:
var <- 0

if (var / 2 == 0) {
  print("Var is even")
} else if (var / 2 == 1) {
  print("Var is odd")
}

for (patient_id in 1001:1005) {
  print(paste("Processing patient", patient_id))
}

month <- 1
total_expenses <- 0

while (total_expenses < 5000) {
  total_expenses <- total_expenses + 600  # monthly expense
  print(paste("Month", month, "- Total:", total_expenses))
  month <- month + 1
}

repeat {
  count_errors <- sample(0:5, 1)  # simulate checking a random error count
  print(paste("Errors found:", count_errors))
  if (count_errors == 0) {
    print("No errors found—stopping check.")
    break
  }
}

for (i in 1:5) {
  if (i == 3) {
    next  # skips the current iteration
  }
  print(i)
}

[1] "Var is even"
[1] "Processing patient 1001"
[1] "Processing patient 1002"
[1] "Processing patient 1003"
[1] "Processing patient 1004"
[1] "Processing patient 1005"
[1] "Month 1 - Total: 600"
[1] "Month 2 - Total: 1200"
[1] "Month 3 - Total: 1800"
[1] "Month 4 - Total: 2400"
[1] "Month 5 - Total: 3000"
[1] "Month 6 - Total: 3600"
[1] "Month 7 - Total: 4200"
[1] "Month 8 - Total: 4800"
[1] "Month 9 - Total: 5400"
[1] "Errors found: 2"
[1] "Errors found: 1"
[1] "Errors found: 1"
[1] "Errors found: 4"
[1] "Errors found: 0"
[1] "No errors found—stopping check."
[1] 1
[1] 2
[1] 4
[1] 5


<h3>Functions</h3>

In [5]:
calculate_total <- function(amount, tax_rate = 0.10) {
  # especifica valor padrão para a tax_rate
  total <- amount + (amount * tax_rate)
  return(total)
}

total1 <- calculate_total(100)        # uses default tax_rate 10%
total2 <- calculate_total(100, 0.15)  # uses specified tax_rate 15%

print(total1)  # Output: 110
print(total2)  # Output: 115

# Lembrar de return nas funções e lembrar de descrever elas com comentários

[1] 110
[1] 115


<h3>Detecção de Erros</h3>

In [6]:
readings <- c(52, 48, NA, 56)

if (any(is.na(readings))) {
  print("Warning: Data contains missing values.")
}


amount_paid <- "twenty"

if (!is.numeric(amount_paid)) {
  print("Error: Amount must be a number.")
}


validate_ridership <- function(data) {
  if (!is.numeric(data)) {
    return("Ridership data must be numeric.")
  }
  if (any(is.na(data))) {
    return("Ridership data contains missing values.")
  }
  "Ridership data is ready to use."
}

[1] "Warning: Data contains missing values."
[1] "Error: Amount must be a number."
